### ISSUE TITLE
Lack of privileges deploying nsx-node-agent on Ubuntu 20.04 docker hosts

### ISSUE THREAD

**Issue by fabiorauber** [vmware/nsx-container-plugin-operator#133]
I'm trying to deploy nsx-ncp-operator v3.1.2 onto Rancher 2.5 RKE-created hosts (Ubuntu 20.04, Kubernetes v1.20). When the nsx-node-agent Daemonset spawns the node-agent containers, they fail to run and display the following error message:

```
NSX 19 - [nsx@6876 comp="nsx-container-node" subcomp="nsx_node_agent" level="ERROR" errorCode="NCP01017"] nsx_ujo.agent.agent Failed to configure nsx_agent_inner: [Errno 13] mount rundir failed: '/host/var/run/netns/nsx-node-agent'
 Traceback (most recent call last):
   File "/usr/local/bin/nsx_node_agent", line 10, in <module>
     sys.exit(main())
   File "/usr/local/lib/python3.6/dist-packages/nsx_ujo/cmd/nsx_node_agent.py", line 17, in main
     agent_main.main()
   File "/usr/local/lib/python3.6/dist-packages/nsx_ujo/common/privilege.py", line 45, in _wrap
     return self._keepalive_wrap(func, *args, **kwargs)
   File "/usr/local/lib/python3.6/dist-packages/nsx_ujo/common/privilege.py", line 56, in _keepalive_wrap
     return super(PrivContextPlus, self)._wrap(func, *args, **kwargs)
   File "/usr/local/lib/python3.6/dist-packages/oslo_privsep/priv_context.py", line 214, in _wrap
     return self.channel.remote_call(name, args, kwargs)
   File "/usr/local/lib/python3.6/dist-packages/oslo_privsep/daemon.py", line 204, in remote_call
     raise exc_type(*result[2])
nsx_ujo.common.exceptions.NSXNodeAgentException: Unexpected error from nsx_node_agent: Failed to configure nsx_agent_inner: [Errno 13] mount rundir failed: '/host/var/run/netns/nsx-node-agent'.
```

After spending some time debugging, I realized the node-agent container couldn't create the network namespace in `/var/run/netns`, so I tried to run it in privileged mode, and it worked. I was wondering whether the container is lacking a capability, but the Daemonset is created by the operator itself, and is configured with the following capabilities:

```
      capabilities:
        add:
        - AUDIT_WRITE
        - DAC_READ_SEARCH
        - NET_ADMIN
        - NET_RAW
        - SYS_ADMIN
        - SYS_PTRACE
```

**Comment by fabiorauber** [comment]
Closing as per https://github.com/vmware/nsx-container-plugin-operator/issues/132.
